# Generated by Django 5.2 on 2025-05-06 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('starting_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parametre_formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('message_text', models.TextField()),
                ('destination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_recues', to=settings.AUTH_USER_MODEL)),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EtudiantRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('starting_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('formation_domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.domaine')),
                ('prof_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parametre_formation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.parametre_formation')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50)),
                ('exam_status', models.CharField(max_length=30)),
                ('minimum_point', models.IntegerField()),
                ('formation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=50)),
                ('video', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('chapter_number', models.IntegerField()),
                ('formation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Formation_by_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('price_cut', models.IntegerField()),
                ('journey_status', models.CharField(max_length=30)),
                ('starting_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField()),
                ('formation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.formation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exam_by_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('note', models.IntegerField()),
                ('min_note', models.IntegerField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.exam')),
                ('formation_by_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.formation_by_user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.IntegerField()),
                ('ref_transaction', models.TextField()),
                ('destination_number', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=20)),
                ('formation_by_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.formation_by_user')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_type', models.TextField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_response_selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('response_note', models.IntegerField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.question')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_response_by_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('exam_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.exam_by_user')),
                ('response_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.exam_response_selection')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.question')),
            ],
        ),
        migrations.CreateModel(
            name='RolesUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Token_souscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('validation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
