# Generated by Django 5.2 on 2025-05-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiantregister',
            name='full_name',
            field=models.CharField(default='Nom Inconnu', max_length=100),
        ),
    ]
