# Generated by Django 5.2 on 2025-05-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_etudiantregister_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiantregister',
            name='lastname',
            field=models.CharField(default='Prenom Inconnu', max_length=100),
        ),
    ]
