# Generated by Django 5.2 on 2025-05-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_etudiantregister_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Brouillon'), (1, 'Publie')], db_index=True, default=0),
        ),
    ]
