# Generated by Django 5.2 on 2025-05-30 22:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0004_alter_formation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaine',
            name='starting_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='domaine',
            name='status',
            field=models.CharField(default='activé', max_length=20),
        ),
    ]
