# Generated by Django 5.2 on 2025-06-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0006_profregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='profregister',
            name='fonction',
            field=models.CharField(default='Aucune fonction', max_length=100),
        ),
    ]
