# Generated by Django 4.2.22 on 2025-06-04 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0007_profregister_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='domaines/images/'),
        ),
        migrations.AlterField(
            model_name='domaine',
            name='closing_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
