# Generated by Django 4.2.22 on 2025-06-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0009_status_alter_formation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chapters/videos/')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='video',
        ),
        migrations.AddField(
            model_name='chapter',
            name='video',
            field=models.ManyToManyField(related_name='chapters', to='cours.video'),
        ),
    ]
