# Generated by Django 4.2.22 on 2025-06-05 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0010_video_remove_chapter_video_chapter_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='closing_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='formation',
            name='starting_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='parametre_formation',
            name='date_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='parametre_formation',
            name='date_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
