# Generated by Django 4.2.22 on 2025-06-10 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0011_alter_formation_closing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='prof_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.profregister'),
        ),
    ]
