# Generated by Django 4.2.22 on 2025-06-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0012_alter_formation_prof_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profregister',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profregister',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
