# Generated by Django 4.2.22 on 2025-06-16 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0013_rename_name_profregister_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation_by_user',
            name='closing_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='formation_by_user',
            name='starting_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
