# Generated by Django 4.2.22 on 2025-06-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0014_alter_formation_by_user_closing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation_by_user',
            name='price_cut',
            field=models.IntegerField(default='Aucun'),
        ),
    ]
