# Generated by Django 4.2.22 on 2025-06-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0015_alter_formation_by_user_price_cut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation_by_user',
            name='journey_status',
            field=models.CharField(default='active', max_length=30),
        ),
    ]
