# Generated by Django 4.2.22 on 2025-06-17 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0016_alter_formation_by_user_journey_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation_by_user',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.etudiantregister'),
        ),
    ]
