# Generated by Django 4.2.22 on 2025-06-17 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0017_alter_formation_by_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payement_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
