# Generated by Django 4.2.22 on 2025-06-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0018_payment_payement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation_by_user',
            name='status',
            field=models.CharField(default='activ', max_length=20),
        ),
    ]
