# Generated by Django 4.2.22 on 2025-06-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0019_alter_formation_by_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paid_amount',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='destination_number',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='payé', max_length=20),
        ),
    ]
