# Generated by Django 4.2.22 on 2025-06-17 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cours', '0020_rename_paid_amount_payment_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='price',
            new_name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='formation_by_user',
            name='closing_date',
        ),
        migrations.RemoveField(
            model_name='formation_by_user',
            name='journey_status',
        ),
        migrations.RemoveField(
            model_name='formation_by_user',
            name='price_cut',
        ),
        migrations.RemoveField(
            model_name='formation_by_user',
            name='starting_date',
        ),
        migrations.RemoveField(
            model_name='formation_by_user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.AddField(
            model_name='formation_by_user',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formation_by_user',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
