# Generated by Django 4.2.22 on 2025-06-18 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0022_formation_by_user_status_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='formation_by_user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cours.formation_by_user'),
        ),
    ]
