# Generated by Django 4.2.22 on 2025-06-19 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0023_alter_payment_formation_by_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='formation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='cours.formation'),
        ),
    ]
