# Generated by Django 4.2.22 on 2025-06-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0024_alter_chapter_formation_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='video',
            new_name='videos',
        ),
    ]
