# Generated by Django 4.2.22 on 2025-07-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0025_rename_video_chapter_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='mikaiadavid@gmail.com', max_length=254, unique=True)),
                ('password', models.CharField(default='1234mika2403', max_length=100)),
            ],
        ),
    ]
